gains:
  pos: {x: 3.7, y: 3.7, z: 8.0}
  vel: {x: 2.4, y: 2.4, z: 3.0}
  rot: {x: 2.3, y: 2.3, z: 0.22}
  #rot: {x: 1.0, y: 1.0, z: 0.22}
  #rot: {x: 1.5, y: 1.5, z: 0.22}
  ang: {x: 0.13, y: 0.13, z: 0.018}
  ki:  {x: 0.0, y: 0.0, z: 0.0}
corrections:
  kf: 3.333333e-09
  r: -9.474645e-03
  p: 4.737322e-03
  # r: 0.0
  # p: 0.0
