sdes:
  rho1: -0.043
  rho2: -0.043
  u: 0.1

vision_gains:
  kprho: 5.0 #3.0
  kpu: 3.0
  kdrho: 1.5
  kdu: 0.6

alpha: 1.0

camera_fps: 78

# Acceleration for the kalman filter
max_accel: 0.5
measurement_noise_rhos: 0.0015
#measurement_noise_rhos: 0.0023
#measurement_noise_rhos: 0.0046
measurement_noise_u: 0.005
#measurement_noise_u: 0.05
