vision_gains:
  kprho: 6.0
  kdrho: 3.3
  kpu: 6.0
  kdu: 1.1
#  kprho: 5.0
#  kpu: 5.0
#  kdrho: 1.7
#  kdu: 0.7

#  kprho: 0.0
#  kpu: 0.0
#  kdrho: 0.0
#  kdu: 0.0

alpha: 1.0

camera_fps: 70

# Acceleration for the kalman filter
max_accel: 1.5
measurement_noise_rhos: 0.0000022
measurement_noise_u: 0.000123

traj_filename: "/home/xua/git/cylinder_perching_3D/trajectories/traj_perch.csv"

need_odom: false
